logo: https://raw.githubusercontent.com/ArazAbishov/thesis/master/images/ferris-climbing.svg
title: An RRB-Tree based vector for Rust
description: A confluently persistent vector implementation for Rust based on RRB-Tree
theme: jekyll-theme-minimal
google_analytics: UA-163945772-3
